name: Echo on Push

on:
  push:
    branches:
      - main   # runs only when pushing to main branch

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "yo! code got pushed 🚀"
